language: go
sudo: false
dist: trusty
addons:
  sonarcloud:
    organization: paysuper
stages:
- test
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: test
    install: true
    script:
    - echo "tests here"
    - sonar-scanner
  - stage: deploy
    services: docker
    install: true
    script:
    - docker run -it -e JENKINS_AUTH_TOKEN=$JENKINS_AUTH_TOKEN -e JENKINS_BUILD_TOKEN=$JENKINS_BUILD_TOKEN
      -e JENKINS_BUILD_PROJECT=$TRAVIS_REPO_SLUG -e JENKINS_BUILD_BRANCH=$TRAVIS_BRANCH
      p1hub/p1jenkinstrigger
notifications:
  slack:
    secure: vPjjJaBJ84wFKifxRPkUfq6+1xV2Qw6vo1Z6+63VfEzdqrMbp7NZbZzJFtD2VurYfNL3fuuLxuK5Sa5wEhGOqegN8QaWZIeNkY7OHvAXpACypDHCPmRwbFyw5z/qQjUI8nk0VeLpv86Gxp1t0z+dje9FuxHsqiPyanL0LKZLpV6YHLiRGTefWpb/sU/kpGItIdaYMhVjKMJ1wUh4mS2GaoeqQX6erES9Rgmu6LEDtIfcP09pOuqdwDnPxgiZ5UWIhHzxdRnbUDD/pAAElh86Zv00yAeMhlIartNgJ3lNMYb6zSJZCwS49KgpRcZk49gy6ViNLSvaBLXEA0KfK5omOw77CZxDTe9RhrHoZpsbsgC0gKkua6V60XmOF5G7Bo98LxQxFUwNhHBG34RJu6ha6o6fgI64++zzjXoo1Zor6i4Gx1YjczvuHIHK3L8X6oP/pzBpfGAy9TBOmCvAbB8v+EmisjS+R4O4uhO3ZUSjTvO4DUgs4m4R7jqIg+3uM/8rpWedurKUBoAyp8sof8WWio/WRNptF4iSzcj15nr5E/1xYDBSIokbWspySE7y/l4iiWJsJ5symrSh0VOoWfC2g2er5cf4TSSxHz7tmX8avTmIaO+BV5caFf6ZxhsuD1UL9PLOUcqjBR+O8uXm7IVjdQDnGDUVUgAnfjbyGEEKcoE=
